spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: DEBUG
    org:
      springframework:
        web: WARN

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

