spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

logging:
  level:
    root: WARN
    org:
      springframework:
        web: WARN

