name: My workflow
on:
  - push
  - pull_request

env:
  SPRING_PROFILES_ACTIVE: development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4.0.0
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Generate keys
        run: make generate_rsa
      - name: Build with gradle
        uses: gradle/gradle-build-action@v3.1.0
        with:
          gradle-version: 8.4
          arguments: build
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco